server:
   port: 9400
logging:
   config: classpath:log4j2.xml

hibernate:
   dialect:
      storage_engine: innodb

spring:
   application:
      name: gateway
   #   cloud:
#      gateway:
#         routes:
#            - id: user-service
#              uri: lb://user-service
#              predicates:
#                 - Path=/user/**
#              filters:
#                 - StripPrefix=1
#                 - name: RequestRateLimiter
#                   args:
#                      key-resolver: "#{@remoteAddrKeyResolver}"
#                      redis-rate-limiter.replenishRate: 1
#                      redis-rate-limiter.burstCapacity: 5
   datasource:
      hikari:
         driver-class-name: net.sf.log4jdbc.DriverSpy
         jdbc-url: jdbc:log4jdbc:mysql://127.0.0.1:3306/gateway?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
         username: root
         password: root

   #   cloud:
#      consul:
#        host: 192.168.0.112
#        port: 8500
#        discovery:
#          register: false
   jpa:
      database: mysql
      generate-ddl: false
      hibernate:
         ddl-auto: none
         naming:
            physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      show-sql: true
      database-platform: org.hibernate.dialect.MySQL55Dialect


   redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      password:
      timeout: 1000  # 连接超时时间（毫秒）

security:
   #   basic:
   #      enabled: false
   oauth2:
      client:
         access-token-uri: http://localhost:9920/oauth/token
         user-authorization-uri: http://localhost:9920/oauth/authorize
         authorities: oauth2
         grant-type: password
         client-secret: 123456
         client-id: client_2
      resource:
         token-info-uri: http://localhost:9920/oauth/check_token
         user-info-uri: http://localhost:9920/uaa/user
         prefer-token-info: true #false使用user-info-uri，true使用token-info-uri
         id: order

#zuul:
#  routes:
#     api:
#       path: /api/**
#       #service-id: consul-miya
#       url: http://localhost:9800